package com.prizm.embedding.exception;

public enum EmbeddingErrorCode {
    OLLAMA_UNAVAILABLE,
    OLLAMA_MODEL_NOT_INSTALLED,
    EMBEDDING_EMPTY_RESPONSE,
    EMBEDDING_DIMENSION_MISMATCH,
    EMBEDDING_INVALID_RESPONSE
}
